#!/bin/sh
# aither-vcs-chain — generated by install_hooks, do not edit by hand.
# Runs the pre-existing hook body (<hook>.org) in a SUBSHELL so an `exec`
# inside it (the original pre-commit ends in `exec python tools/secret_scan.py`)
# cannot terminate this chain, then runs the .d fragments.
#
# Exit-code contract: the FIRST non-zero exit among the .org body and the
# fragments is propagated. A pre-existing gate (the secret scanner) that fails
# must STILL fail the hook — a chain that swallowed it would silently disable
# it. Fragments always run, so a failure in one never silently skips another
# (the post-commit capture still runs even if the CD-autosync trigger failed).
# Both the .org and each fragment run in a SUBSHELL: an `exec` (the real
# pre-commit) or a bare `exit 0` (the lease-check guard) must never terminate
# the chain before the exit-code decision at the bottom.
set -u
HOOK_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
HOOK_NAME="$(basename -- "$0")"

ORG_RC=0
if [ -f "$HOOK_DIR/$HOOK_NAME.org" ]; then
  ( . "$HOOK_DIR/$HOOK_NAME.org" "$@" )
  ORG_RC=$?
fi

FRAG_RC=0
FRAG_DIR="$HOOK_DIR/$HOOK_NAME.d"
if [ -d "$FRAG_DIR" ]; then
  for frag in "$FRAG_DIR"/*; do
    [ -f "$frag" ] || continue
    [ -x "$frag" ] || continue
    ( . "$frag" "$@" ) || { FRAG_RC=$?; break; }
  done
fi

if [ "$ORG_RC" -ne 0 ]; then
  exit "$ORG_RC"
fi
exit "$FRAG_RC"
